# Generated by Django 4.2.1 on 2023-05-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del salon')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('alquiler', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Alquiler')),
                ('rango', models.IntegerField(choices=[(1, 'De 10 a 50'), (2, 'De 50 a 100'), (3, 'De 100 a 500'), (4, 'De 500 a 1000'), (5, 'Mas de 1000')], verbose_name='Rango')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tag')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del espacio')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='salon',
            name='tags',
            field=models.ManyToManyField(to='salones.tags'),
        ),
        migrations.CreateModel(
            name='EspacioSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del espacio')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon')),
            ],
            options={
                'verbose_name': 'Espacio del salon',
                'verbose_name_plural': 'Espacios del salon',
            },
        ),
    ]
