# Generated by Django 4.2.1 on 2023-05-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_alter_salon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
