# Generated by Django 4.2.1 on 2023-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0003_alter_tags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciosalon',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Servicio'),
        ),
    ]
