# Generated by Django 4.2.1 on 2023-05-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0006_espacio_remove_servicios_salon_delete_espaciosalon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salones/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon')),
            ],
            options={
                'verbose_name': 'Imagen del salon',
                'verbose_name_plural': 'Imagenes del salon',
            },
        ),
    ]
