# Generated by Django 4.2.1 on 2023-05-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0008_salon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonimages',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='salones.salon'),
        ),
    ]
